
sudo: required


# Use sed to replace the SSH URL with the public URL, then initialize submodules before_install: 
# Solution ot Permission denied (publickey) error when TravisCI tries to fetch submodules:
# 
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t/24600210
#
git: 
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


# Multi-language build matrix mini tutorial example taken from
#
#   https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
#
matrix:
  include:
#    - language: c
#      before_install: 
#        - sudo apt-get install gfortran
#      script:
#        - make 
#        - ./app/AdapResoMD-hPF.app

    - language: ruby
      rvm: 
        - ruby-head
      install:
        - rmv --default use 2.1.1
        - rvm use 2.1.1
        - sudo gem install rake
        - sudogem install minitest
      before_script:
        - cd ext/FRUIT/fruit_processor_gem
        - rake install
        - cd ..
      script:
        - rake test
    
