
sudo: required


# Use sed to replace the SSH URL with the public URL, then initialize submodules before_install: 
# Solution ot Permission denied (publickey) error when TravisCI tries to fetch submodules:
# 
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t/24600210
git: 
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


matrix:
  include:
    - language: c
      before_install: 
        - sudo apt-get install gfortran
      script:
        - make 
        - ./app/AdapResoMD-hPF.app

    - language: ruby
      addons:
        apt:
          packages:
            - ruby2.0-tcltk
            - libtcl-8.5
            - libtk-8.5
        rvm: 
          - system
        install: 
          - gem install rake
      script: 
        - ruby2.0 -r tcl hello.rb
