language: c

sudo: required

git: 
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules before_install: 
# Solution ot Permission denied (publickey) error when TravisCI tries to fetch submodules:
# 
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t/24600210

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get install gfortran

script:
  - make 
  - ./app/AdapResoMD-hPF.app
  