
sudo: required
language: c

# Use sed to replace the SSH URL with the public URL, then initialize submodules before_install: 
# Solution ot Permission denied (publickey) error when TravisCI tries to fetch submodules:
# 
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t/24600210
#
git: 
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get install gfortran

jobs: 
  include:
    - stage: build
      script:
        - make
    - stage: test
      script:
        - make clean
        - make test
        - ./bin/UnitTests.app
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t f3e28ebb-cea3-4dd4-95c8-d5fca5566ddd
